fix(azure-functions) delayed response
Kong/kong-plugin-azure-functions pull request #1
Opened 2018-06-05 13:53 UTC by bungle

### Summary

Fix `azure-functions` delayed response

2018-06-05 13:54 UTC, bungle commented
When merged, needs tagging.

2018-06-05 22:05 UTC, thibaultcha requested changes

2018-06-05 22:05 UTC, thibaultcha commented on kong/plugins/azure-functions/handler.lua
> +    coroutine.yield()
This shouldn't be needed, the `return` from the line below should already suffice to resume the plugins iterator. Unless there is another reason that I am not seeing, we should not confuse plugin authors into thinking this is necessary.

2018-06-15 20:14 UTC, thibaultcha approved these changes

2018-06-18 11:23 UTC, merged